version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ} # argsのTZはDockerfileで使用
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
    # DB_*の設定値はLaravel設定用の環境変数
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ} # environmentのTZはphp.iniで使用